* Goals
  I encounter more technical terms in Algebra that are somewhat vaguely defined
  every day now. I should collect them together.


* Fibers
  homomorphism phi :: G -> H
  fibers of phi := [[g | phi g == h , g <- G] h <- H] :: [Set G]
  (set of elements in g projecting to a single element in h)
  each fiber is a set corresponding to exactly one element in H.

** Elements with bars over them
   notation for 'this is a fiber'
   also means 'this is a representative for a certain coset'

*** Example
    ZZ to Zn by phi(a + b) = x^{a+b}, so some a+b is a fiber
    this ties back in to the coset example as well. In the integers mod 4,
    bar(3) represents 3, 7, 11, etc (a fiber, because they all go to bar(3))


* Kernel (of a homomorphism phi)
  set [phi g == 1 | g <- G]


* Quotient Group
  Name derived from the quotient group Z / nZ (integers mod n)
  a.k.a. common quotients (equivalence classes)

  G / N = {gN s.t. g in G}

  from wikipedia : a quotient group of G is some partition of G that is a group
  under the operation

  S + T = [ s + t | s <- S t <- T] for partitions S and T.
  (associative as S, T subsets, a monoid because {e} is a subgroup)


* Normal subgroup
  ana^-1 in N (so conjugation can permute the entries of N, , a in N, etc)
  By theorem 3, if phi is a homomorphism from G to H and K = kernel(phi) then
  the left cosets of K in G form a group by

  uK * vK = (uv) K

** Why do we need normal subgroups?

   the operation on left cosets is well defined iff g^-1Ng = N.

** Large 'The Following Are Equivalent' Theorem (3.6)

   1. N a normal subgroup of G
   2. N_G(N) = G
   3. gN = Ng
   4. the operation uK * vK = (uv) K makes the left cosets a group.
   5. gNg^-1 `subset` N

*** For Arbitrary Subgroups

    Proposition 3.1.4 : for N `subgroup` G, left cosets of N partition G

**** Why do the left cosets of a subgroup partition the group itself?

     leftCosets = [(map g N) | g in G] :: [G], and N has the identity element, so
     every element appears in at least one list of leftCosets

**** if u,v in G then uN = vN iff v^-1 u in N

     in particular, uN = vN if u and v represent the same coset (fibers!)


* Relating Orders of Groups and Elements
** Lagrange's Theorem
*** Definition
   say that | G | = | G : H | * | H |
   where | G : H | is the number of left cosets of H in G.
   (for the left cosets to form a group : g*H = H*g)

*** Consequences
   order of an element divides order of the group

   any group of prime order is cyclic and simple (only normal subgroups are
   identity and itself)

** Cauchy's Theorem

  if prime p divides | G | then G has an element of order p.


** Order of the intersection

  if H and K are subgroups, then we
  say that | HK | = | H |*| K | / | H `cap` K |

  This is valid as HK is the union of left cosets of K. HK need not be a
  subgroup (it is if one of the groups is normal!)

*** Corollary 15

   if K `normalSubgroup` G then HK `subgroup` G for any H `subgroup` G.

* Sylow's Theorem

  Weak converse of Lagrange - if | G | = p^a * m for some prime p and p does
  not divide m, then G has a subgroup of order p^a.

** Definitions

   Let a be a natural number.

   1. A group of order p^a is called a p-group.

   2. A subgroup of order p^a is called a p-subgroup.

   3. |G| = p^a * m, p does not divide m, the the subgroup of order p^a is
      called a _Sylow p-subgroup._

   4. Denote the set of Sylow p-subgroups by Syl_p(G).

   5. Denote the number of Sylow p-subgroups by n_p(G).

** Theorems

   Assume that |G| = p^a m, p does not divide m.

   1. Syl_p(G) /= nullset.

   2. P in Syl_p(G) , Q subgroup G, |Q| divides p^a -> exists g in G s.t. Q
      subset gPg^-1. In particular Sylow p-subgroups are conjugate.

   3. n_p(G) congruent to 1 mod p (that is, n_p(G) = 1 + kp). n_p(G) = 1 is
      equivalent to saying that the Sylow p-subgroup of G is normal.

** Sylow 1

   If G is a group with |G| = p1^a1 * p2^a2 ... then G has a subgroup order
   p1^a1. These subgroups are called the Sylow p1-subgroups.

** Sylow 2

   All Sylow p-subgroups are conjugate, and any p-subgroup of G is in Sylow
   p-subgroup.

** Sylow 3

   Let |G| = mp1^a1, so m contains all the other prime factors of |G|. Let n be
   the number of sylow p-subgroups of G. Then

   1. n | m
   2. n congruent 1 mod p.

*** Fun propositions

    G of order 2p -> G cyclic or G isomorphic to D_2p.

    if |G| = pq (both prime), p > q, then

    1. q does not divide p-1 -> G cyclic

    2. q divides p-1 -> G cyclic or G generated by a,b where a^p = b^q = e, ba
       = a^n b.

* Test 2 Review

** General Topics

   Chapters 3 and 4, some of 2

   So, 15 topics, 5 topics per chapter...

*** Parts of 2

    Basic idea - unravel structure by looking at subsets that keep axioms.

    another way - Quotient groups (collapse in to smaller structure)

**** Subgroup criterion

     H Subset G iff

     H .NEQ. nullset
     x,y in H -> xy^-1 in H.

**** Centralizers

     Let A be a nonempty subset of G.

     C_G(A) = {g in G | ga = ag for all a in A}
     (set of elements in G that commute with every element in A)

**** Center

     Special case of centralizer - A is G

     Z(G) = {g in G | gx = xg, forall x in G}
     Z(G) = C_G(G)

**** Normalizers

     Set of elements that permute group under conjugation

     N_G(A) = {g in G | gAg^-1 = A}

**** Orbits

     where can an element go? Anywhere in its orbit.

     orbit(x) = {gx | g in G}

**** Stabilizers

     unmoved (stable) under the action.
     stab(a) = {g * a = a for g in G}

**** Kernels

     Kernel of a homomorphism - elements that map to the identity.

**** Cyclic Subgroups

*** Parts of 3

**** Quotient Groups

     G / N = {gN for g in G}

**** Cosets, Lagrange's Theorem

     Cosets - form from left multiplication.

     left cosets of H = { gH | g in G} for some subgroup H.
     the cosets form a group iff H is normal.

     Important theorem - 3.6

     1. N is a normal subgroup of G

     2. N_G(N) = G (that is, everything normalizes the set N)

     3. gN = Ng (equality of left and right cosets)

     4. the operation uK * vK = (uv) K makes the left cosets a group.

     5. gNg^-1 `subset` N

**** Isomorphism Theorems

     Four of them! They are important.

     1. Consider some phi :: G -> H a homomorphism. Then

        Kernel Phi `normalSubgroup` G
        the image of Phi is a subgroup of H
        the image of Phi is isomorphic to G / Kernel Phi

        so Kernel Phi(G) `normalSubgroup` G
        Phi(G) `normalSubgroup` H
        G / (Kernel Phi(G)) `isomorphic` Image(Phi)

     2. S `subgroup` G, N `normalSubgroup` G. Then

        SN is a subgroup.
        S `intersect` N is a subgroup.
        (SN) / N `isomorphic` S / (S `intersect` N)

     3. K, N `normalSubgroup` G, K `subset` N `subset` G. Then

        N / K is a normal subgroup of G / K
        (G / K) / (N / K) `isomorphic` G / N.

     4. N `normalSubgroup` G, then

        exists bijection
        (set of subgroups containing N) -> (subgroups of G / N)

**** Transpositions

     Any cycle may be written as a composition of _transpositions_, or
     two-cycles.

     (1,2,3) = (1,2)(2,3)

     Call the product

     (x1 - x2)(x1 - x3)(x2 - x3)

     Delta. Permute the indicies by some cycle sigma. Then

     E(sigma) = 1  if sigma(Delta) = Delta
     E(sigma) = -1 if sigma(Delta) = -Delta

***** Example

      Delta = (x1 - x2)(x1 - x3)(x1 - x4)(x2 - x3)(x2 - x4)(x3 - x4)
      sigma = (1,2,4,3)

      sigma(Delta) = (x2 - x4)(x2 - x1)(x2 - x3)(x4 - x1)(x4 - x3)(x1 - x3)

      which has three inversions, so it equals -Delta. Therefore it is an odd
      permutation.

**** Alternating Group

*** Parts of 4

    Permutation Representations of Group Actions

    Groups Acting on Themselves (left multiplication)

    Groups Acting on Themselves (conjugation)

    Sylow Theorems

    Simple Groups

* What Dr. Brown says is on the test

  Pretty much chapters 3 and 4.

  3.1, 3.2, 3.3, (not 3.4), 3.5

  4.1, 4.2, 4.3, (not 4.4), 4.5

** Topics

*** Normalizers, Centralizers, Centers, Stabilizers - relative to actions.

*** Cosets, Lagrange's Theorem

*** Normal subgroups

*** Isomorphism Theorems (all four of them)

    1. Fundamental Theorem - The homomorphic image of a group is a group. The
       image is isomorphic to the first group mod kernel of the mapping. The
       kernel is a normal subgroup.

       This is sometimes called the fundamental theorem of groups and
       homomorphisms.

    2. Diamond Isomorphism Theorem - The picture

                      AB
                     /  \ (B is normal)
                    A    B
                     \  /
                 A intersect B

       AB / B isomorphic to A / (A intersect B)

    3. Invert and Multiply

       (G/N) / (H/N) isomorphic to G / H (justice!)

    4. Lattice, or Correspondence Theorem

*** Cauchy's Theorem

    Every group of order n isomorphic to some subgroup of S_n

*** Permutations and Inversions

    we can talk about the oddness or evenness of a permutation.

    subgroup of even permutations is the alternating group.

*** Groups acting on themselves by left multiplication

    One form of a group action. This can show Cayley's Theorem (left regular
    representation)

*** Groups acting on themselves by conjugation

    Two useful things come from this - orbit stabilizer theorem and Sylow.

    1. G acts on A and S subset A then order G = order (Orbit S) order (Stab S)

    2. Conjugacy classes - N is a normal subgroup of G if and only if N is a
       union of conjugacy classes.

    3. Class Equation - |G| = SUM |orbit g| for non conjugate g in G

       If g in Z(G) then |orbit g| = 1. Therefore we can rewrite this as

       class equation : |G| = |Z(G)| + SUM (g not in center) |Orbit g|

       as the size of conjugacy classes of elements in the center is
       one. Recall : conjugacy class is place we can go from a by gag^-1, which
       (for elements in the center) is always just a.

    4. Sylow Theorems

       1. Technical lemma : all Sylow p-subgroups are conjugate.

       2. More theorems! Fun.

*** Better Approach to the last problem on HW 8

    H8 = < (a b c d), (a b)(c d) > is how we generate subgroups of
    order 8. Then we can conjugate some element of S4 by an element in H8 and
    leave H8, so it is not normal.

*** Left regular representation of a group

    Say that D8 = < r,s | r^4 = s^2 = 1, rsr = s >

    call sigma_r the permutation resulting from left multiplication by r.

    (1 r r^2 r^3)  (s rs r^2s r^3s)

    This is the permutation associated with multiplication by r.

    how about sigma_s?

    (1 s) (r sr) (r^2 sr^2) (r^3) (sr^3)

    Homomorphism between permutation representation and the group, so we can
    get other things in the group this way.
