* Goals
  I encounter more technical terms in Algebra that are somewhat vaguely defined
  every day now. I should collect them together.


* Fibers
  homomorphism phi :: G -> H
  fibers of phi := [[g | phi g == h , g <- G] h <- H] :: [Set G]
  (set of elements in g projecting to a single element in h)
  each fiber is a set corresponding to exactly one element in H.

** Elements with bars over them
   notation for 'this is a fiber'
   also means 'this is a representative for a certain coset'

*** Example
    ZZ to Zn by phi(a + b) = x^{a+b}, so some a+b is a fiber
    this ties back in to the coset example as well. In the integers mod 4,
    bar(3) represents 3, 7, 11, etc (a fiber, because they all go to bar(3))


* Kernel (of a homomorphism phi)
  set [phi g == 1 | g <- G]


* Quotient Group
  Name derived from the quotient group Z / nZ (integers mod n)
  a.k.a. common quotients (equivalence classes)

  G / N = {gN s.t. g in G}

  from wikipedia : a quotient group of G is some partition of G that is a group
  under the operation

  S + T = [ s + t | s <- S t <- T] for partitions S and T.
  (associative as S, T subsets, a monoid because {e} is a subgroup)


* Normal subgroup
  ana^-1 in N (so conjugation can permute the entries of N, , a in N, etc)
  By theorem 3, if phi is a homomorphism from G to H and K = kernel(phi) then
  the left cosets of K in G form a group by

  uK * vK = (uv) K

** Why do we need normal subgroups?
   the operation on left cosets is well defined iff g^-1Ng = N.
** Large 'The Following Are Equivalent' Theorem (3.6)
   1. N a normal subgroup of G
   2. N_G(N) = G
   3. gN = Ng
   4. the operation uK * vK = (uv) K makes the left cosets a group.
   5. gNg^-1 `subset` N

*** For Arbitrary Subgroups

    Proposition 3.1.4 : for N `subgroup` G, left cosets of N partition G

**** Why do the left cosets of a subgroup partition the group itself?
     leftCosets = [(map g N) | g in G] :: [G], and N has the identity element, so
     every element appears in at least one list of leftCosets

**** if u,v in G then uN = vN iff v^-1 u in N
     in particular, uN = vN if u and v represent the same coset (fibers!)


* Relating Orders of Groups and Elements
** Lagrange's Theorem
*** Definition
   say that | G | = | G : H | * | H |
   where | G : H | is the number of left cosets of H in G.
   (for the left cosets to form a group : g*H = H*g)

*** Consequences
   order of an element divides order of the group

   any group of prime order is cyclic and simple (only normal subgroups are
   identity and itself)

** Cauchy's Theorem

  if prime p divides | G | then G has an element of order p.


** Order of the intersection

  if H and K are subgroups, then we
  say that | HK | = | H |*| K | / | H `cap` K |

  This is valid as HK is the union of left cosets of K. HK need not be a
  subgroup (it is if one of the groups is normal!)

*** Corollary 15

   if K `normalSubgroup` G then HK `subgroup` G for any H `subgroup` G.

* Sylow's Theorem

 Weak converse of Lagrange - if | G | = p^a * m for some prime p and p does
 not divide m, then G has a subgroup of order p^a.

** Sylow 1

   If G is a group with |G| = p1^a1 * p2^a2 ... then G has a subgroup order
   p1^a1. These subgroups are called the Sylow p1-subgroups.

** Sylow 2

   All Sylow p-subgroups are conjugate, and any p-subgroup of G is in Sylow
   p-subgroup.

** Sylow 3

   Let |G| = mp1^a1, so m contains all the other prime factors of |G|. Let n be
   the number of sylow p-subgroups of G. Then

   1. n | m
   2. n congruent 1 mod p.

*** Fun propositions

    G of order 2p -> G cyclic or G isomorphic to D_2p.

    if |G| = pq (both prime), p > q, then

    1. q does not divide p-1 -> G cyclic

    2. q divides p-1 -> G cyclic or G generated by a,b where a^p = b^q = e, ba
       = a^n b.

* Test 2 Review

** General Topics

   Chapters 3 and 4, some of 2

   So, 15 topics, 5 topics per chapter...

*** Parts of 2

    Basic idea - unravel structure by looking at subsets that keep axioms.

    another way - Quotient groups (collapse in to smaller structure)

**** Subgroup criterion

     H Subset G iff

     H .NEQ. nullset
     x,y in H -> xy^-1 in H.

**** Centralizers

     Let A be a nonempty subset of G.

     C_G(A) = {g in G | ga = ag for all a in A}
     (set of elements in G that commute with every element in A)

**** Center

     Special case of centralizer - A is G

     Z(G) = {g in G | gx = xg, forall x in G}
     Z(G) = C_G(G)

**** Normalizers

     Set of elements that permute group under conjugation

     N_G(A) = {g in G | gAg^-1 = A}

**** Orbits

     where can an element go? Anywhere in its orbit.

     orbit(x) = {gx | g in G}

    Stabilizers

    Kernels

    Cyclic Subgroups

*** Parts of 3

    Quotient Groups

    Cosets, Lagrange's Theorem

    Isomorphism Theorems

    Transpositions

    Alternating Group

*** Parts of 4

    Permutation Representations of Group Actions

    Groups Acting on Themselves (left multiplication)

    Groups Acting on Themselves (conjugation)

    Sylow Theorems

    Simple Groups


