* 9/12/11
  Can I type faster than I write by hand? We will find out.

** Review of the last homework problem from last time
*** Prove E' = ( E U E')'
    easy version:
    in general we have that (A U B)' = A' U B'
    if x is a limit point of A, it is a limit point of the union.

    Therefore the union of the limit points (A' U B') is a subset of (A U B)'

    harder version:
    if x in (A U B)' then every neighborhood Nr(x) containes some point of A U B distinct
    from x. If we can always take y in A, then

    x in A' -> x in A' U B' .

    suppose that

    exists Nr(x) such that (Nr(x) \ {x} ) intersect A = nullset

    then forall r > 0, we must have (Nr(x) \ {x} ) intersect B /= nullset
    therefore x in B'

    To be in A', we need the neighborhood. Some rs, point in A; others, point in B.

    Application : (E U E')' = E' U E'' = E' U E' = E'

    Part a

    Suppose that x in (E')'. To show: x in E'

    By definition, (write definitions and follow your nose), forall r > 0

    (Nr(x) \ {x} ) intersect E' /= nullset

    choose y in (Nr(x) \ {x} ) \{x} intersect E'

    choose r' > 0 s.t. Nr'(y) subset Nr(x) \ {x}

    so y in E' so there exists z in Nr'(y) with z in E, z /= y.

    Therefore z in Nr(x) \ {x}, which is true for r > 0 -> x in E'.


*Number 8*

E subset R^2, E open -> E subset E'

E open -> exists r > 0 with Nr(x) subset E

for x in E subset R^2, Nr(x) infinite -> for r small enough,
(Nr(x) \ {x}) intersect E /= nullset

Actual lecture begins here

Connectedness
for subsets A and B of some metric space X, A and B are separated if

A intersect (closure B) = nullset and (closure A) intersect B = nullset

Example:

A = (0,1) and B = (1,2) not separated

A set E subset X is connected if E is not disconnected

E is disconnected -> E has a disconnection -> E = A U B and A,B separated.

Equivalently - E is disconnected if E = A (disjoint union) B (write it as such, union of two sets minus the intersection)
    where A and B are both (E-open OR E-closed OR A is both E-open and E-closed)

Now lets go to R^1.

Theorem 2.42 - A nonempty subset E subset R1 is connected iff E has the following properties:
(for a < b)

1. x in E, y in E, x < z < y -> z in E
2. E is an interval, i.e. E = one of (-inf, b) (-inf, b], [a,b], (a,b], [a,b), R, etc
3.

Proof

Let a = inf E
Let b = sup E

proceed to show that one of the cases of (2) is valid.

Connectedness proof

Proof - negate both conditions - prove that E in R disconnected iff not 2.42

    (trick - set defined by a property. Negate step by step to show x `notin` A)

    not [(forall x, y in E with x < y) (and forall z in R with x < z < y), then z in E]

    Therefore we need to produce a z such that x < z < y but z `notin` E

    Set Az = E intersect (-inf, z), Bz = E intersect (z, +inf)

    for x in Az, Az /= nullset
    for y in Bz, Bz /= nullset

    z notin E, Az union z union Bz = R

    Note that Az intersect (closure Bz) = nullset, and (closure A) intersect Bz = nullset
    so E is disconnected (as z `notin` E)

    (other direction) assume E disconnected, so E = A (disjoint union) B with A, B
    nonempty and separated. Pick x in A, y in B : WLOG x < y.

    (we will use completeness of the reals)

    define z = sup (A intersect [x,y])
    then z in (closure A)
         (by a previous result, sup f in (closure F) for F nonempty, bounded above, subset of R)

    so z `notin` B as the sets are separated.
    so x \leq z < y

    if z notin A then must have x < z < y (strictness) and we are done.

    If z in A, then z notin (closure B) implies (exists z_1 with z < z_1 < y) and z_1 notin B
       Then x < z_1 < y and z_1 notin B. As z_1 > x, z_1 notin A so z_1 notin E and we are done.




* 9/14/11
** Hints for hw5
   G open, V1 open -> G intersect V1 /= nullset

   G1 open -> V1 intersect G1 = new (??) open

   Choose V2 open, (closure V2) subset V1 intersect G1.

   G2 dense -> G2 intersect V2 /= nullset (it is a subset of G1)

   #17

   Use Baire's theorem
   for some E1, take the real number line and throw out everything that is not
   of the form 0.4... and 0.7... and use uniqueness of decimal expansions (keep
   it closed at each set)
   Hard part - invent suitable notation for dealing with it. The intersection
   should be nonempty, but nowhere dense, but perfect, any point in the
   intersection (neighborhood around it) for fine enough the

   property - always have endpoints (like Cantor) so we have
   perfect/uncountable (strings of 4s and 7s is the same as strings of 1s and
   0s, which is uncountable.)

   # 18
   There exists a perfect set with no rationals (answer! it does exist.)
   so rationals Q intersect [0,1] is countable (as Q is countable)

   call this list r_1, r_2, ...

   create an interval around each and remove them, but leave some space between
   each (irrationals between rationals)


** Upcoming Dates
   HW5 due on Monday (extra credit as well)
   HW6 due on Friday (connectedness)
