* 9/12/11
  Can I type faster than I write by hand? We will find out.

** Review of the last homework problem from last time
*** Prove E' = ( E U E')'
    easy version:
    in general we have that (A U B)' = A' U B'
    if x is a limit point of A, it is a limit point of the union.

    Therefore the union of the limit points (A' U B') is a subset of (A U B)'

    harder version:
    if x in (A U B)' then every neighborhood Nr(x) containes some point of A U B distinct
    from x. If we can always take y in A, then

    x in A' -> x in A' U B' .

    suppose that

    exists Nr(x) such that (Nr(x) \ {x} ) intersect A = nullset

    then forall r > 0, we must have (Nr(x) \ {x} ) intersect B /= nullset
    therefore x in B'

    To be in A', we need the neighborhood. Some rs, point in A; others, point in B.

    Application : (E U E')' = E' U E'' = E' U E' = E'

    Part a

    Suppose that x in (E')'. To show: x in E'

    By definition, (write definitions and follow your nose), forall r > 0

    (Nr(x) \ {x} ) intersect E' /= nullset

    choose y in (Nr(x) \ {x} ) \{x} intersect E'

    choose r' > 0 s.t. Nr'(y) subset Nr(x) \ {x}

    so y in E' so there exists z in Nr'(y) with z in E, z /= y.

    Therefore z in Nr(x) \ {x}, which is true for r > 0 -> x in E'.


*Number 8*

E subset R^2, E open -> E subset E'

E open -> exists r > 0 with Nr(x) subset E

for x in E subset R^2, Nr(x) infinite -> for r small enough,
(Nr(x) \ {x}) intersect E /= nullset

Actual lecture begins here

Connectedness
for subsets A and B of some metric space X, A and B are separated if

A intersect (closure B) = nullset and (closure A) intersect B = nullset

Example:

A = (0,1) and B = (1,2) not separated

A set E subset X is connected if E is not disconnected

E is disconnected -> E has a disconnection -> E = A U B and A,B separated.

Equivalently - E is disconnected if E = A (disjoint union) B (write it as such, union of two sets minus the intersection)
    where A and B are both (E-open OR E-closed OR A is both E-open and E-closed)

Now lets go to R^1.

Theorem 2.42 - A nonempty subset E subset R1 is connected iff E has the following properties:
(for a < b)

1. x in E, y in E, x < z < y -> z in E
2. E is an interval, i.e. E = one of (-inf, b) (-inf, b], [a,b], (a,b], [a,b), R, etc
3.

Proof

Let a = inf E
Let b = sup E

proceed to show that one of the cases of (2) is valid.

Connectedness proof

Proof - negate both conditions - prove that E in R disconnected iff not 2.42

    (trick - set defined by a property. Negate step by step to show x `notin` A)

    not [(forall x, y in E with x < y) (and forall z in R with x < z < y), then z in E]

    Therefore we need to produce a z such that x < z < y but z `notin` E

    Set Az = E intersect (-inf, z), Bz = E intersect (z, +inf)

    for x in Az, Az /= nullset
    for y in Bz, Bz /= nullset

    z notin E, Az union z union Bz = R

    Note that Az intersect (closure Bz) = nullset, and (closure A) intersect Bz = nullset
    so E is disconnected (as z `notin` E)

    (other direction) assume E disconnected, so E = A (disjoint union) B with A, B
    nonempty and separated. Pick x in A, y in B : WLOG x < y.

    (we will use completeness of the reals)

    define z = sup (A intersect [x,y])
    then z in (closure A)
         (by a previous result, sup f in (closure F) for F nonempty, bounded above, subset of R)

    so z `notin` B as the sets are separated.
    so x \leq z < y

    if z notin A then must have x < z < y (strictness) and we are done.

    If z in A, then z notin (closure B) implies (exists z_1 with z < z_1 < y) and z_1 notin B
       Then x < z_1 < y and z_1 notin B. As z_1 > x, z_1 notin A so z_1 notin E and we are done.




* 9/14/11
** Hints for hw5
   G open, V1 open -> G intersect V1 /= nullset

   G1 open -> V1 intersect G1 = new (??) open

   Choose V2 open, (closure V2) subset V1 intersect G1.

   G2 dense -> G2 intersect V2 /= nullset (it is a subset of G1)

   #17

   Use Baire's theorem
   for some E1, take the real number line and throw out everything that is not
   of the form 0.4... and 0.7... and use uniqueness of decimal expansions (keep
   it closed at each set)
   Hard part - invent suitable notation for dealing with it. The intersection
   should be nonempty, but nowhere dense, but perfect, any point in the
   intersection (neighborhood around it) for fine enough the

   property - always have endpoints (like Cantor) so we have
   perfect/uncountable (strings of 4s and 7s is the same as strings of 1s and
   0s, which is uncountable.)

   # 18
   There exists a perfect set with no rationals (answer! it does exist.)
   so rationals Q intersect [0,1] is countable (as Q is countable)

   call this list r_1, r_2, ...

   create an interval around each and remove them, but leave some space between
   each (irrationals between rationals)


** Upcoming Dates
   HW5 due on Monday (extra credit as well)
   HW6 due on Friday (connectedness)

** Definition : K in X is compact means:
   given any open cover {G_alpha : alpha in A} of K (so K is in the union of
   all G_alpha) there is a finite subcover consisting of a finite collection of
   alphas such that K subset union over alpha of G_alpha

*** Examples:

   K = (0,1) is covered by {(0,3/4),(1/2,1)} (finite cover)

   another cover: (1/n, 1) for n in NN, has no finite subcover.

   Not hard to show not compact just from creating a cover with no finite
   subcover.

   For the homework problem {0} U {1/n}, we can use Heine-Borel, but it is more
   instructive to use the definition.

*** TODO Archimedes Corollary
    all but finitely many something something. Fill this out.

*** Nested interval theorem

    for nullset /= In = [a_n, b_n] superset Im
*** Heine-Borel

    Not closed implies not compact.
    Alternatively, we can say that if K is closed and bounded in R then it is
    compact.

*** Compactness of [0,1]

**** Classic version

     Take [0,1] - it is compact (proof : by contradiction : suppose that there
     exists an open cover of [0,1] {G_alpha} with no finite subcover. Note that
     then {G_alpha} covers [0,1/2] and [1/2,1].

     Step 1: assumption implies that {G_alpha} has a cover of at least one of
     [0,1/2] and [1/2,1] . Therefore we have a finite subcover for each, and
     their union is finite and covers [0,1]: a contradiction.

     Part 2: Pick I1 = one of the two so {G_alpha} has no finite subcover of
     I1.

     Get I1 superset I2 ... superset In - by nested interval theorem -> the
     intersection is nonempty - in fact, it must be a single point, x0, since
     the length of In -> 0 (cannot be two things in the intersection, the
     length between them always decreases)

     but x0 in G_alpha for some alpha. and I subset G_alpha0 since the length
     goes to zero. Therefore there is a finite subcover of In.

     Therefore for n large enough, we have a finite subcover of In after all; a
     contradiction.)

**** Other version - not in our book.

     How do we distinguish between [0,1] intersect Q and [0,1] ? completeness.

     Suppose {G_alpha} is an open cover of [0,1]. Our goal is to find some
     finite subcover. Define a set

     E = {x in [0,1] | {G_alpha} has a finite subcover of [0,x]}

     Check : E /= nullset. We are allowed to take x = 0 in E as 0 in G_alpha0
     (as {G_ALPHA} covers [0,1]) so [0,0] has a finite subcover.

     E is bounded above by 1, so by the Least Upper Bound property for RR,

     x0 = sup E exists, 0 leq x0 leq 1

     Claim : x0 exists and x0 = 1. Then we are done.

     x0 exists -> If x0 = 0 we are done.

         Assume x0 > 0 so x0 in [0,1] -> some G_alpha0prime in {G_alpha} such
         that G_alpha0prime open -> exists delta > 0 s.t.

         N_delta(x_0) = (x0 - delta, x0 + delta) subset of G_alpha0prime

         Then x0 - delta < x0 -> exists s in E s.t. x0 - delta leq s leq x0

         Then {G_alpha} has a finite subcover over [0,s]. Then throw in to that
         union of sets G_alpha0prime which covers [0,x0].

         In conclusion : x0 in E (used t < x0 -> t not an upper bound)

     Part 2: Suppose that x0 /= 1, so x0 < 1.

     x0 in G_alpha0prime and (x0 - s, x0 + s) in G_alpha0prime. For x0 in E
     there exists some union of Gs s.t. their union covers [0,x0] then that
     union with G_alpha0prime is a superset of [0, x + delta] -> 1 in E and 1
     is least upper bound -> {G_alpha} has a finite subcover of [0,1].



