* General Terminology

** Geostrophic

*** Dr. Iliescu

    Several forcing effects - wind, solar, ice.
    wind is the major one in the middle of the ocean.

    air, in rotation, organizes itself in to columns (constant in z direction)
    this is why we study 2D equations.

    Geostrophic - organized in z-independent fashion
    Quasi-Geostrophic - integrate over z and use some average; not balanced
    (not steady state)

    Charney Jules - invented QGE


* Describing Vorticity and Stream Functions

** Vorticity

*** From lec16.pdf

    Starting point for large-scale circulation
    Similar to 2D incompressible flow (Navier-Stokes)
    main difference - Vorticity variable is 3D Laplacian of Stream Function


** Stream Function

*** From ch13.pdf

    Psi is the stream function
    Say that geostrophic flow is parallel to constant lines Psi
    Strength proportional to 'spacing of iso-lines of Psi'

**** Equation

     Laplacian_p of Psi = dv_g/dx - du_g/dy ~ Zeta_rel

*** From BSL

    Easy problems - remove all but one direction.
    More dimensions? Simplify by eliminating the pressure term.
    'eliminate the pressure by taking the curl of the equation of motion'

**** Formulation for planar (2D) flows

     stream function Psi
     express the two nonvanishing components of the velocity as Psi derivatives
     choose these so that the equation of continuity works automatically


* Physical Constants

** Rossby Number

*** From lec16.pdf

    Ro = V / (fL)
    where V is the speed of a horizontal current
          L is the horizontal scale
          f is the coriolis parameter (some times a constant)

*** From Introduction to Geophysical Fluid Dynamics

    (Page 481) For Ro < 1 : rotational effects significant
    Ro is the ratio of inertial to rotational forces
    Purely geostrophic - balance between pressure gradient and coriolis
    (steady-state)

    Ro_T = 1 / (Omega T) where Omega is the angular rotation rate of the planet
    and T is the time scale. ('time span over which the flow field evolves
    substantially')


** Eckman Number

*** From Introduction to Geophysical Fluid Dynamics

    (Page 482) Ek = nu_E / (Omega H^2)


** f-plane

*** From ch13.pdf

    Coriolis parameter f - some trigonometric function of latitude (ch13)
    f-plane approximation - replace occurances of f with a constant f0

**** From ch13.pdf : Better Approximation - Beta-plane

     Allow f to vary in north-south direction linearly:

     f = f0 + beta * (y - y0)

     where beta = (df/ (a d phi) )_0 = 2 * Omega * cos phi_0 / a
     (so beta is the linearization constant for moving in direction y)

     typical choice - phi_0 = 45 degrees -> beta = 1.62e-11 m^-1 s^-1


* Notation

  (a;b,c) is something like a * (b x c)


* Important Books

**  Joseph Pedlosky - Geophysical Fluid Dynamics

    Rigorous derivation of QGE and the length scale analysis.

