* General Terminology

** Geostrophic

*** Dr. Iliescu

    several forcing effects - wind, solar, ice.
    wind is the major one in the middle of the ocean.

    air, in rotation, organizes itself in to columns (constant in z direction)
    this is why we study 2D equations.

    Geostrophic - organized in z-independent fashion
    Quasi-Geostrophic - integrate over z and use some average; not balanced
    (not steady state)

    Charney Jules - invented QGE

*** From Introduction to Geophysical Fluid Dynamics (Chapter 1)

    Quasi-Geostrophic models - Phillips (1956) developed a 2-layer model that
    predicted realistic cyclones in the wrong places and times

    QG models fail near the equator (only remedy - use full equations. Bad!)
    full equations - more sensitive to initial data, need smaller time steps.


* Motivation

** From Introduction to Geophysical Fluid Dynamics (Chapter 1)

*** Goals

    Numerical GFD - not limited to weather prediction.
    Gain insight in to particular phenomena, role of forces, etc
    'Only way to experiment with the planet'
    hindcast, nowcast, forecast - estimate previous, current, or future data
    based on limited information.

*** Difficulties

    As Lorenz showed - inherently unstable.
    Richardson tried with a room full of people with slide rules, with T = 6
    hours; far too unstable.

    Better choice than Richardson - Charney picked a more simplified model,
    less variation in pressure. Far more successful.


* Scale of Motion

** From Introduction to Geophysical Fluid Dynamics (Chapter 1)

   Determine if a physical process is dynamically important (does it induce a
   large change?)

   Key scales - time, length, velocity

   other scales - stratification (changes in density) is measured by change in
   density per length (Delta rho and H)

*** Example for a ship

    Consider waves of the same length as the ship L, velocities the same as the
    ship U, and time scale L/U.

*** Rotation and Scale

    If the fluid flow evolves on a time scale of over a day we should consider
    the earth's rotation. So consider rotation for QGE.

*** Stratification and Scale

    Gravity sorts fluids with dense on bottom and less dense on top, but fluid
    flows tend to work against this

    If we raise heavy fluids we gain potential energy and lose kinetic; we can
    gain kinetic energy by lowering heavy fluids again. We can form another
    ratio:

    0.5 * rho_0 * U^2 / (Delta rho * g * H)

    that is, kinetic / potential energies. If this is about one then moving the
    fluid greatly changes velocity; very small, insufficient kinetic energy to
    perturb the flow greatly; very large, effect does not matter (lose little
    kinetic energy). _Therefore we can only ignore stratification if it is much
    larger than one._

    If epsilon = time of revolution / (L / U) ~ 0.5 * rho_0 * U^2 / (Delta
    rho * g * H) ~ 1 then rotation and stratification are both important, but
    neither dominates. This gives

    L ~ 1/Omega * sqrt (Delta rho / rho0 * g * H)

    as a length scale. Therefore for the ocean we should pick about 60km as the
    length scale and 4 m/s as the velocity scale.

*** Scale analysis and Finite Differences

    Strong relationship between scale analysis and numerical requirements.

    Since we have a discrete time scale, we approximate derivatives by

    du/dt ~ U/T d^2u / dt^2 ~ U/T^2

    First-order finite differences are pretty bad - better approximations given
    in later chapters.

    Atlantic Ocean - to resolve eddies and stratified water masses we need
    about 10 million grid points for step size of 10^4 meters.

**** Aliasing

     Finite Difference methods fail when the time step is not low
     enough. Lowest sampling frequency is the Nyquist frequency.

* Ocean and Atmosphere Distinctions

** From Introduction to Geophysical Fluid Dynamics (Chapter 1)

   Flows of several kilometers to earth-scale

   Oceans - islands and continents get in the way. Driven by many things (wind,
   tides, temperature delta between air and water, etc)
   Atmosphere - deal with moisture. Driven by solar energy.


* Describing Vorticity and Stream Functions

** Vorticity

*** From lec16.pdf

    Starting point for large-scale circulation
    Similar to 2D incompressible flow (Navier-Stokes)
    main difference - Vorticity variable is 3D Laplacian of Stream Function

** Stream Function

*** From http://www.see.ed.ac.uk/~johnc/teaching/fluidmechanics4/2003-04/fluids2/node31.html

    Need to solve, in 2D, for u and v in the incompressibility term

    du/dx + dv/dy = 0

    Alternatively, we could solve for ONE term (the so-called stream function)
    where

    u = dPsi/dy, v = -dPsi/dx

    which automatically satisfies continuity.

**** Source of name

     Psi constant along some streamline - hence the name stream function

     This is valid as by definition (on a stream line) dx/u = dy/v (so dPsi = 0)

*** From ch13.pdf

    Psi is the stream function
    Say that geostrophic flow is parallel to constant lines Psi
    Strength proportional to 'spacing of iso-lines of Psi'

**** Equation

     Laplacian_p of Psi = dv_g/dx - du_g/dy ~ Zeta_rel

*** From BSL

    Easy problems - remove all but one direction.
    More dimensions? Simplify by eliminating the pressure term.
    'eliminate the pressure by taking the curl of the equation of motion'

**** Formulation for planar (2D) flows

     stream function Psi
     express the two nonvanishing components of the velocity as Psi derivatives
     choose these so that the equation of continuity works automatically

* Forces

  Ambient rotation introduces two additional forces

** Coriolis Force

*** From Introduction to Geophysical Fluid Dynamics (Chapter 1)

    Major effect - vertical rigidity
    For rapid, homogeneous fluids - motion strictly columnar.
    Large scale flows - not perfectly columnar

*** From Introduction to Geophysical Fluid Dynamics (Chapter 2)

    We observe fluid mechanics in relation to the rotating system. Boundaries
    are not moving with respect to the earth.

    We may do a long derivation

** Centrifugal Force

*** From Introduction to Geophysical Fluid Dynamics

    No strong effect on geophysical flows (recall that we ignore the z direction)


* Physical Constants

** Rossby Number

*** From lec16.pdf

    Ro = V / (fL)
    where V is the speed of a horizontal current
          L is the horizontal scale
          f is the coriolis parameter (some times a constant)

*** From Introduction to Geophysical Fluid Dynamics

    (Page 481) For Ro < 1 : rotational effects significant
    Ro is the ratio of inertial to rotational forces
    Purely geostrophic - balance between pressure gradient and coriolis
    (steady-state)

    Ro_T = 1 / (Omega T) where Omega is the angular rotation rate of the planet
    and T is the time scale. ('time span over which the flow field evolves
    substantially')

** Eckman Number

*** From Introduction to Geophysical Fluid Dynamics

    (Page 482) Ek = nu_E / (Omega H^2)

** f-plane

*** From ch13.pdf

    Coriolis parameter f - some trigonometric function of latitude (ch13)
    f-plane approximation - replace occurances of f with a constant f0

**** From ch13.pdf : Better Approximation - Beta-plane

     Allow f to vary in north-south direction linearly:

     f = f0 + beta * (y - y0)

     where beta = (df/ (a d phi) )_0 = 2 * Omega * cos phi_0 / a
     (so beta is the linearization constant for moving in direction y)

     typical choice - phi_0 = 45 degrees -> beta = 1.62e-11 m^-1 s^-1

* Notation

  (a;b,c) is something like a * (b x c)


* Boussinesq

  Starting equation for QGE

** Wikipedia

   eliminate vertical coordinate from flow, but retain some vertical effects.
   (interested in wave propagation - not much in vertical direction)

* QGE Soup

** Ingredients

   Rossby Number

   Boussinesq - the starting equation.

   Stream Functions

   Vorticities


** Result

   partial q / partial t + J(Psi, q) = 0

   where Psi is the stream function
   q = Laplacian Psi
     + (partial / partial z) (f_0^2 / N^2 (partial Psi / partial z))
     + beta_0 * y
   N^2(z) = -(g/rho_0) * d(bar(rho)) / dz (should be a constant, roughly, for
   water)

* Important Books

**  Joseph Pedlosky - Geophysical Fluid Dynamics

    Rigorous derivation of QGE and the length scale analysis.

    Dr. Iliescu says -- somewhat dry. Majda better.


** Andrew Majda - Introduction to PDEs and waves for the atmosphere and ocean

   Only currently available mathematical text on these equations. I bought a copy.

* Properties of the Fluid

** From Introduction to Geophysical Fluid Dynamics

   stratified flows - sorted by density (gravitational force important)
   perturbations maintained over time can cause fluid flows (like temperature
   deltas)

* Implementation
